version: '2'
volumes:
  mysql-dev:
    external: true
    driver: 'null'
services:
  mysql-lb:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 3306:3306/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: <database>
      MYSQL_PASSWORD: <password>
      MYSQL_ROOT_PASSWORD: <root password>
      MYSQL_USER: <username>
    stdin_open: true
    volumes:
    - mysql-dev:/var/lib/mysql
    tty: true
    ports:
    - 3306:3306/tcp
    labels:
      io.rancher.container.pull_image: always
