version: '2'
volumes:
  mysql-demo:
    external: true
    driver: 'null'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: mysql-demo
      MYSQL_PASSWORD: fantastic
      MYSQL_ROOT_PASSWORD: awesome
      MYSQL_USER: youguys
    stdin_open: true
    volumes:
    - mysql-demo:/var/lib/mysql
    tty: true
    ports:
    - 3306:3306/tcp
    labels:
      io.rancher.container.pull_image: always
